[run]
branch = true
source = [
    "projects/document_formats/src",
    "projects/duckdb_parsing/src",
    "projects/github_reports/src",
    "projects/rich_cli/src",
    "projects/testing_async/src",
    "projects/testing_avro/src",
    "projects/testing_cython/src",
    "projects/testing_dbml/src",
    "projects/testing_jinja/src",
    "projects/testing_nocodb/src",
    "projects/testing_orc/src",
    "projects/testing_redis/src",
    "projects/testing_sqlglot/src",
    "projects/testing_struct/src",
    "projects/yaml_parsing/src",
]
