# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
---
# profiles:
#   `skip`: Skip the service
#   `build`: Build the service

services:
  redis:
    image: redis:7.4
    container_name: Redis
    ports: ["6379:6379"]
    profiles: ["build"]
